export const SKILLS = [
  { slug: "find-skills", title: "find-skills", owner: "Vercel Labs", repo: "vercel-labs/skills", category: "Agent workflows", installs: "2,8 M", audit: "Référencé", command: "npx skills add vercel-labs/skills --skill find-skills", description: "Découvrir et installer des skills adaptés à une tâche directement depuis une session d’agent." },
  { slug: "frontend-design", title: "frontend-design", owner: "Anthropic", repo: "anthropics/skills", category: "Design & UI", installs: "733,8 k", audit: "Audité", command: "npx skills add anthropics/skills --skill frontend-design", description: "Concevoir des interfaces frontend cohérentes, accessibles et prêtes pour une implémentation réelle." },
  { slug: "vercel-react-best-practices", title: "vercel-react-best-practices", owner: "Vercel Labs", repo: "vercel-labs/agent-skills", category: "React", installs: "600,3 k", audit: "Audité", command: "npx skills add vercel-labs/agent-skills --skill vercel-react-best-practices", description: "Appliquer les recommandations de performance et d’architecture React et Next.js de Vercel." },
  { slug: "microsoft-foundry", title: "microsoft-foundry", owner: "Microsoft", repo: "microsoft/azure-skills", category: "Microsoft 365", installs: "499,9 k", audit: "Officiel", command: "npx skills add microsoft/azure-skills --skill microsoft-foundry", description: "Mettre en œuvre des solutions d’IA Microsoft Foundry avec les procédures officielles Azure." },
  { slug: "azure-ai", title: "azure-ai", owner: "Microsoft", repo: "microsoft/azure-skills", category: "Microsoft 365", installs: "495,6 k", audit: "Officiel", command: "npx skills add microsoft/azure-skills --skill azure-ai", description: "Déployer et exploiter des services Azure AI selon les pratiques recommandées par Microsoft." },
  { slug: "skill-creator", title: "skill-creator", owner: "Anthropic", repo: "anthropics/skills", category: "Agent workflows", installs: "337,8 k", audit: "3 audits réussis", command: "npx skills add https://github.com/anthropics/skills --skill skill-creator", description: "Créer, tester et améliorer des skills avec des évaluations structurées et des benchmarks." },
  { slug: "pdf", title: "pdf", owner: "Anthropic", repo: "anthropics/skills", category: "Documents", installs: "171,0 k", audit: "Audité", command: "npx skills add anthropics/skills --skill pdf", description: "Lire, produire et contrôler des documents PDF dans des workflows agentiques." },
  { slug: "pptx", title: "pptx", owner: "Anthropic", repo: "anthropics/skills", category: "Documents", installs: "192,6 k", audit: "Audité", command: "npx skills add anthropics/skills --skill pptx", description: "Créer et réviser des présentations PowerPoint avec une méthode de contrôle dédiée." },
] as const;

export function getSkill(slug: string) { return SKILLS.find((skill) => skill.slug === slug); }
