"use client";
import { useMemo, useState } from "react";

const ARTICLES=[
  {tag:"Gouvernance",title:"Construire une bibliothèque de prompts qui reste vraiment utile",summary:"Versionnement, responsabilités, retours utilisateurs et critères de qualité.",time:"12 min"},
  {tag:"Méthode",title:"Les variables @ sans friction",summary:"Transformer un prompt générique en modèle personnalisable sans le rendre illisible.",time:"7 min"},
  {tag:"Sécurité",title:"Protéger les données avant de parler à une IA",summary:"Les contrôles simples à effectuer avant chaque partage de document.",time:"9 min"},
  {tag:"Microsoft 365",title:"Copilot : choisir le bon contexte au bon moment",summary:"Document, page, réunion ou dépôt : comment fournir un contexte suffisant.",time:"8 min"},
  {tag:"Analyse",title:"Mesurer la qualité d’un prompt sans intuition",summary:"Une grille pragmatique pour comparer fiabilité, précision et utilité.",time:"11 min"},
  {tag:"Productivité",title:"Quand créer une chaîne de prompts",summary:"Découper une mission complexe en étapes contrôlables et réutilisables.",time:"6 min"},
];

export default function BlogPage(){const[query,setQuery]=useState("");const[active,setActive]=useState(0);const filtered=useMemo(()=>ARTICLES.filter((article)=>`${article.tag} ${article.title}`.toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr"))),[query]);const featured=ARTICLES[active]??ARTICLES[0]!;return <div className="blog-v5"><header><div><h1>Blog & ressources</h1><p>Des idées en mouvement pour mieux utiliser l’IA dans un contexte professionnel.</p></div><label><span>Rechercher</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Un sujet, une méthode..."/></label></header><section className="article-marquee" aria-label="Articles en mouvement"><div>{[...ARTICLES,...ARTICLES].map((article,index)=><button key={`${article.title}-${index}`} onClick={()=>setActive(index%ARTICLES.length)}><span>{article.tag}</span>{article.title}<b>↗</b></button>)}</div></section><section className="blog-v5-feature"><div><span>{featured.tag}</span><h2>{featured.title}</h2><p>{featured.summary}</p><button>Lire l’article · {featured.time} →</button></div><aside><i/><i/><i/><strong>INSEPTI<br/>IDEAS<br/>LAB</strong></aside></section><section className="blog-v5-list">{filtered.map((article,index)=><button key={article.title} onClick={()=>setActive(ARTICLES.indexOf(article))}><span>{String(index+1).padStart(2,"0")}</span><div><small>{article.tag} · {article.time}</small><h2>{article.title}</h2><p>{article.summary}</p></div><b>→</b></button>)}</section></div>}
