"use client";
import { useState } from "react";
import { DifficultyTag } from "@/components/PromptTags";

const EXERCISES = [
  { level: "Débutant" as const, title: "Transformer une réunion Teams en plan d’action", description: "Cadrez la synthèse, les responsables, les échéances et les décisions sans inventer d’informations.", brief: "Rédigez un prompt pour transformer la transcription d’une réunion Teams en tableau : décision, action, responsable, échéance et point à confirmer.", expected: ["décision", "responsable", "échéance", "confirmer"] },
  { level: "Débutant" as const, title: "Préparer un e-mail client vérifiable", description: "Produisez un message professionnel à partir de faits fournis, avec une gestion explicite des informations manquantes.", brief: "Demandez un e-mail de suivi client de 150 mots maximum, fondé uniquement sur les faits transmis et signalant les informations manquantes.", expected: ["150", "faits", "manquantes", "ton"] },
  { level: "Intermédiaire" as const, title: "Comparer deux offres sans biais", description: "Définissez une grille pondérée, rendez les hypothèses visibles et séparez faits et interprétations.", brief: "Construisez un prompt qui compare deux offres techniques selon coût, sécurité, délai, réversibilité et risques. Exigez une note, les preuves et les hypothèses.", expected: ["coût", "sécurité", "preuves", "hypothèses"] },
  { level: "Intermédiaire" as const, title: "Auditer une réponse potentiellement hallucinée", description: "Forcez le modèle à isoler chaque affirmation, qualifier sa preuve et proposer une vérification.", brief: "Écrivez un prompt d’audit qui classe les affirmations en vérifiées, incertaines ou non sourcées, puis propose une méthode de vérification.", expected: ["vérifiées", "incertaines", "sources", "vérification"] },
  { level: "Avancé" as const, title: "Revue de code sécurisée assistée par IA", description: "Faites analyser un changement de code sans exposer de secret et avec une sortie directement exploitable par l’équipe.", brief: "Créez un prompt de revue de pull request : contexte, diff, risques de sécurité, performance, tests manquants, sévérité et correctif minimal.", expected: ["diff", "sécurité", "tests", "sévérité", "correctif"] },
  { level: "Avancé" as const, title: "Concevoir un workflow agentique contrôlé", description: "Découpez une mission en agents spécialisés avec entrées, sorties, droits et points d’arrêt humains.", brief: "Concevez un workflow pour analyser un appel d’offres : collecte, conformité, technique, chiffrage et synthèse. Ajoutez les validations humaines et les critères d’arrêt.", expected: ["conformité", "validation", "critères", "arrêt", "synthèse"] },
];

export default function ExercisesPage(){const[active,setActive]=useState<number|null>(null);const[answer,setAnswer]=useState("");const[score,setScore]=useState<number|null>(null);const exercise=active===null?null:EXERCISES[active];function evaluate(){if(!exercise)return;const normalized=answer.toLocaleLowerCase("fr");const hits=exercise.expected.filter((word)=>normalized.includes(word)).length;setScore(Math.round((hits/exercise.expected.length)*100));}return <div className="exercises-v4"><header><h1>Exercices professionnels</h1><p>Des scénarios concrets pour les réunions, les clients, l’analyse, le code et les workflows agentiques.</p></header><section className="exercise-day"><div><small>EXERCICE DU JOUR · 12 MIN</small><h2>Auditer une réponse potentiellement hallucinée</h2><p>Transformez une réponse convaincante en ensemble d’affirmations vérifiables, sourcées et qualifiées.</p></div><button className="primary-action" onClick={()=>{setActive(3);setScore(null)}}>Lancer l’exercice</button></section><div className="exercise-cards">{EXERCISES.map((item,index)=><article key={item.title}><header><DifficultyTag value={item.level}/><b>{String(index+1).padStart(2,"0")}/{String(EXERCISES.length).padStart(2,"0")}</b></header><h2>{item.title}</h2><p>{item.description}</p><button onClick={()=>{setActive(index);setAnswer("");setScore(null)}}>{active===index?"En cours":"Commencer"} →</button></article>)}</div>{exercise&&<section className="exercise-workbench"><header><div><DifficultyTag value={exercise.level}/><h2>{exercise.title}</h2></div><button onClick={()=>setActive(null)} aria-label="Fermer">×</button></header><p>{exercise.brief}</p><textarea value={answer} onChange={(event)=>setAnswer(event.target.value)} placeholder="Écrivez votre proposition de prompt..."/><footer><button className="primary-action" disabled={answer.trim().length<40} onClick={evaluate}>Évaluer ma proposition</button>{score!==null&&<div><strong>{score} %</strong><span>{score===100?"Les éléments essentiels sont présents. Faites maintenant tester le prompt par un collègue.":"Éléments à expliciter : "+exercise.expected.filter((word)=>!answer.toLocaleLowerCase("fr").includes(word)).join(", ")}</span></div>}</footer></section>}</div>}
