"use client";

import { useEffect, useRef, useState } from "react";
import type { BufferGeometry, Material, Mesh, Object3D, Texture } from "three";

export function HomeNetworkScene({ label, fr = true }: { label: string; fr?: boolean }) {
  const mountRef = useRef<HTMLDivElement>(null);
  const [status, setStatus] = useState<"loading"|"ready"|"fallback">("loading");
  useEffect(() => {
    const mount = mountRef.current; if (!mount) return;
    let disposed=false, frame=0, visible=true; let resizeObserver:ResizeObserver|undefined; let intersectionObserver:IntersectionObserver|undefined; let cleanup=()=>{};
    void Promise.all([import("three"),import("three/addons/loaders/GLTFLoader.js")]).then(([THREE,{GLTFLoader}])=>{
      if(disposed)return;
      const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:"high-performance"}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.08; renderer.domElement.className="home-network-canvas"; renderer.domElement.setAttribute("aria-hidden","true"); mount.appendChild(renderer.domElement);
      const scene=new THREE.Scene(); const camera=new THREE.PerspectiveCamera(35,1,.1,100); camera.position.z=10;
      const particles=new THREE.Group(); particles.position.z=-1.8; scene.add(particles); const rig=new THREE.Group(); rig.rotation.set(Math.PI/2-.06,-.08,0); scene.add(rig);
      scene.add(new THREE.HemisphereLight(0xeaffdf,0x031014,2.7)); const key=new THREE.DirectionalLight(0xcaff9d,4.5); key.position.set(4,5,7); scene.add(key); const glow=new THREE.PointLight(0x75c044,12,18); glow.position.set(-3,2,4); scene.add(glow); const cyan=new THREE.PointLight(0x24d4d8,5,14); cyan.position.set(4,-2,2); scene.add(cyan);
      const count=170, home=new Float32Array(count*3), velocity=new Float32Array(count*3), colors:number[]=[]; const green=new THREE.Color("#9be15d"), teal=new THREE.Color("#24d4d8");
      for(let i=0;i<count;i++){const a=i*.61803398875*Math.PI*2; const radius=1.5+((i*37)%100)/100*4.1; home[i*3]=Math.cos(a)*radius; home[i*3+1]=Math.sin(a)*radius*.58; home[i*3+2]=Math.sin(a*1.7)*.8-1; const c=green.clone().lerp(teal,(i%11)/18); colors.push(c.r,c.g,c.b)}
      const geometry=new THREE.BufferGeometry(); geometry.setAttribute("position",new THREE.BufferAttribute(home.slice(),3)); geometry.setAttribute("color",new THREE.Float32BufferAttribute(colors,3)); const material=new THREE.PointsMaterial({size:.115,vertexColors:true,transparent:true,opacity:.82,depthWrite:false,blending:THREE.AdditiveBlending}); particles.add(new THREE.Points(geometry,material));
      const geometries:BufferGeometry[]=[geometry],materials:Material[]=[material]; let model:Object3D|undefined; let dragging=false,shiftDrag=false,lastX=0,lastY=0,pointerX=99,pointerY=99,targetX=0,targetY=0,targetYaw=-.08,targetPitch=Math.PI/2-.06,targetScale=1.23,currentScale=1.23;
      const reduced=()=>document.documentElement.dataset.motion==="soft";
      const reset=()=>{targetX=0;targetY=0;targetYaw=-.08;targetPitch=Math.PI/2-.06;targetScale=1.23};
      const pointer=(event:PointerEvent)=>{const b=mount.getBoundingClientRect();pointerX=((event.clientX-b.left)/b.width-.5)*10;pointerY=-((event.clientY-b.top)/b.height-.5)*5.8};
      const down=(event:PointerEvent)=>{dragging=true;shiftDrag=event.shiftKey;lastX=event.clientX;lastY=event.clientY;mount.setPointerCapture(event.pointerId);mount.closest("figure")?.classList.add("is-dragging")};
      const move=(event:PointerEvent)=>{pointer(event);if(!dragging)return;const dx=event.clientX-lastX,dy=event.clientY-lastY;if(shiftDrag){targetX=THREE.MathUtils.clamp(targetX+dx*.012,-2.7,2.7);targetY=THREE.MathUtils.clamp(targetY-dy*.012,-1.7,1.7)}else{targetYaw+=dx*.018;targetPitch=THREE.MathUtils.clamp(targetPitch+dy*.012,.35,2.65)}lastX=event.clientX;lastY=event.clientY};
      const up=(event:PointerEvent)=>{dragging=false;if(mount.hasPointerCapture(event.pointerId))mount.releasePointerCapture(event.pointerId);mount.closest("figure")?.classList.remove("is-dragging")};
      const wheel=(event:WheelEvent)=>{event.preventDefault();targetScale=THREE.MathUtils.clamp(targetScale-event.deltaY*.0008,.75,1.8)};
      const render=(time=0)=>{if(disposed||!visible)return;const pos=geometry.attributes.position!.array as Float32Array;const force=reduced()?.004:.011;for(let i=0;i<count;i++){const j=i*3,px=pos[j]??0,py=pos[j+1]??0,pz=pos[j+2]??0,hx=home[j]??0,hy=home[j+1]??0,hz=home[j+2]??0;let vx=velocity[j]??0,vy=velocity[j+1]??0,vz=velocity[j+2]??0;const dx=px-pointerX,dy=py-pointerY,d=Math.sqrt(dx*dx+dy*dy);if(d<1.45){const push=(1-d/1.45)*force;vx+=dx/(d+.01)*push;vy+=dy/(d+.01)*push}vx=(vx+(hx-px)*.012)*.91;vy=(vy+(hy-py)*.012)*.91;vz=(vz+(hz-pz)*.01)*.91;velocity[j]=vx;velocity[j+1]=vy;velocity[j+2]=vz;pos[j]=px+vx+Math.sin(time*.0005+i)*.00035;pos[j+1]=py+vy+Math.cos(time*.00045+i)*.0003;pos[j+2]=pz+vz}geometry.attributes.position!.needsUpdate=true;if(!dragging)targetYaw+=reduced()?.00025:.00075;rig.rotation.y+=(targetYaw-rig.rotation.y)*.12;rig.rotation.x+=(targetPitch-rig.rotation.x)*.12;rig.rotation.z=Math.sin(targetYaw*.45)*.08;rig.position.x+=(targetX-rig.position.x)*.09;rig.position.y+=(targetY-rig.position.y)*.09;currentScale+=(targetScale-currentScale)*.09;const breath=1+(reduced()?.012:.028)*Math.sin(time*.0011);rig.scale.setScalar(currentScale*breath);if(!dragging)rig.position.y+=Math.sin(time*.0008)*(reduced()?.00008:.00022);particles.rotation.z=Math.sin(time*.00008)*.025;renderer.render(scene,camera);frame=requestAnimationFrame(render)};
      new GLTFLoader().load("/brand/insepti-logo-3d.glb",gltf=>{model=gltf.scene;let index=0;model.traverse(child=>{const mesh=child as Mesh;if(!mesh.isMesh)return;const source=Array.isArray(mesh.material)?mesh.material:[mesh.material];const branded=source.map(()=>{const greenTone=index++%3!==1;const m=new THREE.MeshStandardMaterial({color:greenTone?0x75c044:0x77868b,emissive:greenTone?0x183b0d:0x0b1417,emissiveIntensity:greenTone?.52:.15,metalness:greenTone?.3:.7,roughness:.28});materials.push(m);return m});mesh.material=Array.isArray(mesh.material)?branded:branded[0]!});const box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());model.position.sub(center);model.scale.setScalar(6.4/Math.max(size.x,size.y*1.45,size.z));rig.add(model);setStatus("ready")},undefined,()=>setStatus("fallback"));
      const resize=()=>{const w=Math.max(mount.clientWidth,1),h=Math.max(mount.clientHeight,1);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}; resizeObserver=new ResizeObserver(resize);resizeObserver.observe(mount);intersectionObserver=new IntersectionObserver(([entry])=>{const next=Boolean(entry?.isIntersecting);if(next===visible)return;visible=next;if(visible)frame=requestAnimationFrame(render);else cancelAnimationFrame(frame)},{threshold:.03});intersectionObserver.observe(mount);mount.addEventListener("pointerdown",down);mount.addEventListener("pointermove",move);mount.addEventListener("pointerup",up);mount.addEventListener("pointercancel",up);mount.addEventListener("pointerleave",()=>{if(!dragging){pointerX=99;pointerY=99}});mount.addEventListener("wheel",wheel,{passive:false});mount.addEventListener("dblclick",reset);resize();render();
      cleanup=()=>{cancelAnimationFrame(frame);mount.removeEventListener("pointerdown",down);mount.removeEventListener("pointermove",move);mount.removeEventListener("pointerup",up);mount.removeEventListener("pointercancel",up);mount.removeEventListener("wheel",wheel);mount.removeEventListener("dblclick",reset);model?.traverse(child=>{const mesh=child as Mesh;if(mesh.isMesh){mesh.geometry.dispose();(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(m=>Object.values(m).forEach(v=>{if((v as Texture)?.isTexture)(v as Texture).dispose()}))}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove()};
    }).catch(()=>setStatus("fallback")); return()=>{disposed=true;resizeObserver?.disconnect();intersectionObserver?.disconnect();cleanup()};
  },[]);
  return <figure className={`home-network-scene is-${status}`} aria-label={label}><div ref={mountRef} className="home-network-mount"/><figcaption><span><i/> INSEPTI Antistress</span><b>{fr?"Glisser : tourner · Maj : déplacer · molette : zoom · double-clic : recentrer":"Drag: rotate · Shift: move · wheel: zoom · double-click: reset"}</b></figcaption></figure>;
}
